// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inzcazqhirnmrksbnwjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluemNhenFoaXJubXJrc2Jud2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MjE2NTMsImV4cCI6MjA3OTE5NzY1M30.t204V9Xxa_lnyYi78lBiZNpZYl0iZsOF1A7GAgilGJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});